AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/*
    - config/initializers/**
    - db/migrate/**

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/* # devise generated code
