AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/*
    - config/initializers/**
    - db/migrate/**

Rails:
  Enabled: true

# devise generated code needs to be excluded
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/*

# controller methods are sometimes longer
Metrics/MethodLength:
  Max: 50
  Exclude:
    - lib/restricted_usernames.rb

# rails controllers can get very long
Metrics/ClassLength:
  Enabled: false

# Screens can handle longer lines than 80 chars
Metrics/LineLength:
  Max: 120

# Check with yard instead.
Style/Documentation:
  Enabled: false
