test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development:
 adapter: sqlite3
 database: db/development.sqlite3
 pool: 5
 timeout: 5000

staging:
 adapter: postgresql
 encoding: utf8
 database: mailman_production
 pool: 5
 host: localhost
 username: rails
 password: <%= ENV['APP_DATABASE_PASSWORD'] %>


production:
 adapter: postgresql
 encoding: utf8
 database: mailman_production
 pool: 5
 host: localhost
 username: rails
 password: <%= ENV['APP_DATABASE_PASSWORD'] %>
